channel: stable-4.12
version: 4.12.35
subscriptions:
  - name: rhacs-operator
    namespace: rhacs-operator
    channel: stable
    source: redhat-operators
  - name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: latest
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
acs:
  enabled: true
sealedsecrets:
  enabled: true
gitops:
  enabled: true
knative:
  enabled: false
kafka:
  enabled: false