apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-application-set
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: primar-placement
      requeueAfterSeconds: 180
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: operators-mew-{{name}}
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        targetRevision: restructure
        path: "infrastructure/operators"
      destination:
        namespace: operators-{{name}}
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
