apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-application-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        revision: HEAD
        directories:
          - path: "infrastructure/operators"
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        targetRevision: restructure
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
