{{- if eq .Values.hyperconverged.enabled true }}
kind: HyperConverged
apiVersion: hco.kubevirt.io/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    deployOVS: 'false'
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec: {}
{{- end }}
