{{- if eq .Values.multiclusterhub.enabled true }}
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: multiclusterhub
  namespace: open-cluster-management
spec: {}
{{- end }}
